# 请勿修改!
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: rural-express
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/rural_express?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库初始化配置
    sql-script-encoding: UTF-8
  sql:
    init:
      mode: never
      schema-locations: classpath:db/init.sql
  
  # Redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 10000
    
  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis-Plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ruralexpress.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-prefix: t_

# 日志配置
logging:
  level:
    com.ruralexpress: debug
    org.springframework.web: info

# 应用自定义配置
app:
  # JWT配置
  jwt:
    # JWT加密密钥 (安全的32字节/256位密钥)
    secret-key: 'ruralExpress2023SecretKey123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    # token有效期 (7天)
    token-validity-in-seconds: 604800
    # token有效期 (30天) - 记住我
    token-validity-in-seconds-for-remember-me: 2592000
  
  # 文件上传配置
  upload:
    # 上传文件存储路径
    file-path: 'upload/'
    # 允许上传的文件类型
    allowed-file-types: 'jpg,jpeg,png,gif'
    # 最大文件大小
    max-file-size: 10485760

# 文件上传自定义配置
file:
  upload:
    # 上传文件基础路径
    base-path: ${user.dir}/uploads
    # 访问域名
    base-url: http://localhost:8080/api/uploads

# 图片上传路径配置
upload:
  # 评价图片保存路径
  review-image:
    path: review 